<?php

/**
 * @file
 * Installation and update functions for the Legal module.
 */

/**
 * Implements hook_schema().
 */
function legal_schema() {
  $schema['legal_conditions'] = array(
    'fields'      => array(
      'tc_id'      => array(
        'type'       => 'serial',
        'unsigned'   => FALSE,
        'not null'   => TRUE,
        'disp-width' => 10,
      ),
      'version'    => array(
        'type'       => 'int',
        'unsigned'   => FALSE,
        'not null'   => TRUE,
        'default'    => 0,
        'disp-width' => 11,
      ),
      'revision'   => array(
        'type'       => 'int',
        'unsigned'   => FALSE,
        'not null'   => TRUE,
        'default'    => 0,
        'disp-width' => 11,
      ),
      'langcode'   => array(
        'description' => t("The language code of this legal condition."),
        'type'        => 'varchar',
        'length'      => '12',
        'not null'    => TRUE,
        'default'     => '',
      ),
      'conditions' => array(
        'type'     => 'text',
        'size'     => 'big',
        'not null' => TRUE,
      ),
      'date'       => array(
        'type'       => 'int',
        'unsigned'   => FALSE,
        'not null'   => TRUE,
        'default'    => 0,
        'disp-width' => 11,
      ),
      'extras'     => array('type' => 'text'),
      'changes'    => array('type' => 'text'),
      'format'     => array(
        'type'     => 'varchar',
        'not null' => FALSE,
        'length'   => 255,
      ),
    ),
    'primary key' => array('tc_id'),
  );

  $schema['legal_accepted'] = array(
    'fields'      => array(
      'legal_id' => array(
        'type'       => 'serial',
        'unsigned'   => FALSE,
        'not null'   => TRUE,
        'disp-width' => 10,
      ),
      'version'  => array(
        'type'       => 'int',
        'unsigned'   => FALSE,
        'not null'   => TRUE,
        'default'    => 0,
        'disp-width' => 11,
      ),
      'revision' => array(
        'type'       => 'int',
        'unsigned'   => FALSE,
        'not null'   => TRUE,
        'default'    => 0,
        'disp-width' => 11,
      ),
      'langcode' => array(
        'description' => t("The language code of this accepted legal condition."),
        'type'        => 'varchar',
        'length'      => '12',
        'not null'    => TRUE,
        'default'     => '',
      ),
      'uid'      => array(
        'type'       => 'int',
        'unsigned'   => FALSE,
        'not null'   => TRUE,
        'default'    => 0,
        'disp-width' => 10,
      ),
      'accepted' => array(
        'type'       => 'int',
        'unsigned'   => FALSE,
        'not null'   => TRUE,
        'default'    => 0,
        'disp-width' => 11,
      ),
      'tc_id'    => array(
        'type'       => 'int',
        'unsigned'   => FALSE,
        'not null'   => TRUE,
        'default'    => 0,
        'disp-width' => 10,
      ),
    ),
    'indexes'     => array('uid' => array('uid')),
    'primary key' => array('legal_id'),
  );

  return $schema;
}

/**
 * Implements hook_update_last_removed().
 */
function legal_update_last_removed() {
  return 7103;
}

/**
 * Convert variables to config.
 */
function legal_update_1000() {
  $config = config('legal.settings');
  $config->set('user_profile_display', (int) update_variable_get('legal_user_profile_display', 1));
  $config->set('accept_every_login', (int) update_variable_get('legal_accept_every_login', 0));
  $config->set('except_roles', update_variable_get('legal_except_roles', array()));
  $config->set('display', (int) update_variable_get('legal_display', 0));
  $config->set('link_target', update_variable_get('legal_link_target', ''));
  $config->save();
  update_variable_del('legal_user_profile_display');
  update_variable_del('legal_accept_every_login');
  update_variable_del('legal_except_roles');
  update_variable_del('legal_display');
  update_variable_del('legal_link_target');
}

/**
 * Change language columns to langcode.
 */
function legal_update_1001() {
  $spec = array(
    'description' => 'The language code of this legal condition.',
    'type' => 'varchar',
    'length' => 12,
    'not null' => TRUE,
    'default' => '',
  );
  db_change_field('legal_conditions', 'language', 'langcode', $spec);
  $spec['description'] = 'The language code of this accepted legal condition.';
  db_change_field('legal_accepted', 'language', 'langcode', $spec);
}
